version: "3.8"
services:
  web:
    ports:
      - "3000:80"

    depends_on:
      - redis

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - PORT=80
    
    build: .
  
  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - ./redis-data:/data
    restart: always
